import type { NextPage } from 'next'
import Head from 'next/head'
import { motion, useMotionValue, useTransform } from "framer-motion"
import { useEffect } from 'react';

const Home: NextPage = () => {

  const x = useMotionValue(0);
  const y = useMotionValue(0);

  function handleMouse(event) {
    if (event.type === 'mousemove' && event.buttons === 1) {
    const rect = event.currentTarget.getBoundingClientRect();

    const determineNumber = () => {
      const x = event.clientX - rect.left;
      const y = event.clientY - rect.top;

      if (y >= 180 && y <= 400) {
        return event.clientX - rect.right
      }
      // if y value is between 180-400 then invert x number
      return x;
    }
    x.set(determineNumber());
    console.log('this is x ' + x.get());
    };
  }
  // useEffect(() => {
  // console.log();
  // });


  const cursorRange = [-400, -1, 0, 400,]
  const rotateRange = [360, 181, 0, 180]
  const rotateTop = useTransform(x, cursorRange, rotateRange);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Cosmographia
        </h1>
        <div className='bottomContainer'>
          <motion.img style={{
            originY: 0.54, rotate: rotateTop,
          }} whileTap={{ cursor: "grabbing" }} className='topImage' src='/top.png' alt='volvelleTop' draggable="false" />
          <motion.div className='topContainer' whileTap={{ cursor: "grabbing" }}
            onMouseDown={handleMouse} onMouseMove={handleMouse} draggable="false" />          
          <img draggable="false" className='bottomImage' src='/JRL20114423.jpg' alt='volvelle' />
        </div>
      </main>

      <footer>
        <span>2022</span>
      </footer>
    </div>
  )
}

{/* <motion.img style={{ originY: 0.54 }} drag='x' whileDrag={{ rotate: 20 }} dragConstraints={{ left: 0, right: 0, top: 0, bottom: 0 }} whileTap={{ cursor: "grabbing" }} className='topImage' src='/top.png' alt='volvelleTop' draggable="false" /> */ }

export default Home
