import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import bottomImage from '../assets/JRL20114423.jpg'
import topImage from '../assets/top.png'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Cosmographia
        </h1>
        <div className='bottomContainer'>
        <img className='topImage' src='/top.png' alt='volvelleTop' />
        <img className='bottomImage' src='/JRL20114423.jpg' alt='volvelle' />
        </div>

      </main>

      <footer>
        <span>2022</span>
      </footer>
    </div>
  )
}

export default Home
